#{{ if .Values.nginx.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  labels:
    poc: "poc-1"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: poc
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/mamonteiro-devops/poc-nginx-ingress
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
#{{ end }}